### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by wezm** [rust-analyzer/rust-analyzer.github.io#10]
Hi I noticed the following broken links on the website:

- Posts link in header
- Changelog link in header
- The [find usages implemented post](https://rust-analyzer.github.io/2019/11/13/find-usages.html)

**Comment by matklad** [comment]
Good catch, thanks!

The first two are fixed, the second one would be tricky to fix...

**Comment by matklad** [comment]
I've temporary rolled back the recent blog restructurings, will install the required redirects tomorrow

**Comment by matklad** [comment]
fixed this a while ago actually, the old links now redirect
