### ISSUE TITLE
Disable toast notifications

### ISSUE THREAD

**Issue by cortopy** [rust-analyzer/rust-analyzer.github.io#102]
I've started getting some new toast notifications in the bottom right part of the screen. I personally find them very annoying as every time cargo check fails I get a pop up saying "cargo check failed". I already get the wiggly lines so don't need that distraction

I went through all settings but couldn't find a way to disable them. Could this be added please?

Version: 0.2.554

**Comment by flodiebold** [comment]
The notifications are just for the initial check, which is needed to compile proc macros and build files. There's already a fix in nightly that will make that build only build those, and not error on other things.

**Comment by cortopy** [comment]
thanks!
