### ISSUE TITLE
Add some more IDE configurations in the user manual

### ISSUE THREAD

**Issue by woshilapin** [rust-analyzer/rust-analyzer.github.io#180]
In the User manual `manual.adoc`, there is a section to help everyone to set up their favorite IDE/editor. This is great.

I could probably provide a PR for at least two more text editors ([Kakoune](https://kakoune.org/) and [Helix](https://docs.helix-editor.com/)).

But first, I wanted to know if this kind of changes would be welcomed. I could understand the desire to keep the list short and only about mainstream IDE/editors. Tell me if you'd like me to contribute or else, you can just close the issue.

**Comment by flodiebold** [comment]
We have a section for juCi++, which I have never even heard of. So I think it'd be fine to add Kakoune and Helix.
