### ISSUE TITLE
Open VSX publishing abandoned

### ISSUE THREAD

**Issue by almindor** [rust-analyzer/rust-analyzer.github.io#187]
I've noticed that [rust-analyzer](https://open-vsx.org/extension/matklad/rust-analyzer) in `open-vsx` marketplace has been stuck on version `0.2.853` for some time.

What's the official rust-analyzer stance on 3rd party marketplaces for VS-code clone extensions? I'm wondering how best we could get this updated on that marketplace, it's used by a fair amount of people that use OS-code (e.g. any arch linux user).

**Comment by almindor** [comment]
Hups my bad. posted in wrong repo

**Comment by lnicola** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/11080#issuecomment-1148229791.
