### ISSUE TITLE
Can't turn off special font style for mutable variables

### ISSUE THREAD

**Issue by proehlen** [rust-analyzer/rust-analyzer.github.io#188]
Hi, [the manual says](https://rust-analyzer.github.io/manual.html#semantic-style-customizations) the following about this feature:

> You can customize the look of different semantic elements in the source code. For example, mutable bindings are underlined by default and you can override this behavior by adding the following section to your settings.json

However, there doesn't seem to be a way to set this to "normal" - ie turn the feature off.  The only options it will accept for that setting are blank - in which case I get underlined text - or variations on bold, italic, strike through etc.

Is there a way to disable this altogether? I personally find different font styles in my source to be really distracting.

Thanks

**Comment by proehlen** [comment]
Sorry, nevermind, I figured it out:

```
    "editor.semanticTokenColorCustomizations": {
        "enabled": false
    }
```

**Comment by lnicola** [comment]
This used to work, I think it might be a regression or a VS Code change. Your workaround doesn't disable only the underlines, but the whole semantic colorization feature (which does much more).
