### ISSUE TITLE
Add first-class support for thiserror

### ISSUE THREAD

**Issue by Bajix** [rust-analyzer/rust-analyzer.github.io#189]
In a situation in which a function returns a thiserror error enum and a new error type is used, it would be extremely helpful if Rust Analyzer could recommend adding that error to that enum or otherwise creating a new error type. Done properly this could take the pain out of error type management

**Comment by Aloso** [comment]
You're in the wrong repo. This repo is only for rust-analyzer's website, not rust-analyzer itself. Please file this issue [here](https://github.com/rust-lang/rust-analyzer/issues).
