### ISSUE TITLE
format code fail, if there is an async function

### ISSUE THREAD

**Issue by wugifer** [rust-analyzer/rust-analyzer.github.io#190]
I wrote this:
```
fn                  test() {
    let a=1;
}
```
after formatted, I got this:
```
fn test() {
    let a = 1;
}
```
that is ok.

but when I wrote this:
```
async fn                  test() {
    let a=1;
}

fn test2           (){}
```

after formatted, nothing happen.

version: rust-analyzer v0.3.1301

**Comment by wugifer** [comment]
rustup 1.24.3 (ce5817a94 2021-05-31)

**Comment by wugifer** [comment]
rustfmt 1.4.38-stable (db9d1b20 2022-01-20)

**Comment by wugifer** [comment]
Cargo.toml:

[package]
edition = "2021"

**Comment by wugifer** [comment]
add edition   = "2018" in rustfmt.toml, done

**Comment by Aloso** [comment]
Please report issues in [rust-lang/rust-analyzer](https://github.com/rust-lang/rust-analyzer/) in the future. This repo is only for the rust-analyzer _website_.
