### ISSUE TITLE
auto completion for 'fn' does not work when there is no curly bracket '{ }' on the 'fn' above

### ISSUE THREAD

**Issue by lenardlopez** [rust-analyzer/rust-analyzer.github.io#192]
VS Code 1.74.1
Rust-analyzer v0.3.1317
Rust 1.65.0

Example below to simulate the issue.
But if I add curly bracket '{ }' on 'fn' 'struct' auto complete works.

![2022-12-17 13 04 54](https://user-images.githubusercontent.com/95019851/208226362-3b1b66b4-2d2e-421d-9511-0f2ae26fa3cd.jpg)

**Comment by flodiebold** [comment]
This repo is for the rust-analyzer website. Can you report this at https://github.com/rust-lang/rust-analyzer?

**Comment by lenardlopez** [comment]
Ok. Thanks!
