### ISSUE TITLE
Rename Symbol (F2) in VSCode does not work

### ISSUE THREAD

**Issue by gimmi** [rust-analyzer/rust-analyzer.github.io#195]
Hello, 

With a clean installation of VSCode

```
Visual Studio Code
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z (5 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

```

and just `rust-lang.rust-analyzer` version `0.3.1361`  installed, the rename symbol functionality (that is, <kbd>F2</kbd> key) is not working.

![RenameBug](https://user-images.githubusercontent.com/6589/212534167-30c77e76-8552-4cd0-8df8-181e3840ec53.gif)

**Comment by lnicola** [comment]
Does it work if you remove the tokio attribute? It doesn't matter that the code won't compile any more.

**Comment by Aloso** [comment]
Note that this is the wrong issue tracker, it is only for RA's website. Issues for rust-analyzer are tracked [here](https://github.com/rust-lang/rust-analyzer).

**Comment by gimmi** [comment]
Moved in the appropriate repo
