### ISSUE TITLE
Possible error in the documentation

### ISSUE THREAD

**Issue by NomisIV** [rust-analyzer/rust-analyzer.github.io#198]
I'm trying to disable checking of all targets, and the documentation says the option should be `rust-analyzer.check.allTargets`, which didn't work. However `rust-analyzer.checkOnSave.allTargets` (as copied from other GitHub issues: https://github.com/rust-lang/rust-analyzer/issues/10716#issuecomment-962697981) does work. Is this an error with the generated documentation, or is it some kind of version mismatch between the documentation and the version of rust-analyzer that I'm using?

**Comment by bjorn3** [comment]
Which version of rust-analyzer are you using? checkOnSave.allTargets was somewhat recently renamed to check.allTargets.

**Comment by NomisIV** [comment]
Ah that makes sense. I'm currently using `rust-analyzer 2023-01-09`.
