### ISSUE TITLE
Perhaps a memory leak in vscode/Windows

### ISSUE THREAD

**Issue by PRTGC** [rust-analyzer/rust-analyzer.github.io#199]
Hi...

It seems there may be a memory problem in Windows / vscode...
After it runs for a while I get this:
```
Image			PID	HFaults/sec	Commit (KB)	Working Set (KB)	Shareable (KB)	Private (KB)
rust-analyzer.exe	2628	0		24,842,288	733,548			12,400		721,148
rust-analyzer.exe	7972	0		13,256,732	47,144			18,668		28,476
```
It releases when I restart it...

**Comment by lnicola** [comment]
Is that 24 and 13 GB? Did you have two instances running? Anyway, it's hard to tell without a way to reproduce the issue.

PS: you want to file this in https://github.com/rust-lang/rust-analyzer/.

**Comment by PRTGC** [comment]
Hi...
Actually there is 1 instance of vscode and are 6 instances of rust-analyzer...
Not sure what is going on...
But, I'll post it there
Thanks
   JR
