### ISSUE TITLE
What is happening with donations?

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer.github.io#200]
It's [been a while](https://rust-analyzer.github.io/blog/2021/08/03/financial-report-3.html) since the last financial report.

The [OpenCollective page](https://opencollective.com/rust-analyzer) says that there are 164,774.60 EUR in the account, and only 22,000 EUR have been withdrawn. Does that mean that donations aren't needed? I think the people donating would appreciate an update to know what will happen with the money.

**Comment by lnicola** [comment]
There's actually a new(er) report on this at https://mobile.twitter.com/axboe/status/1634961201926127616.

**Comment by Aloso** [comment]
Good to know! Any reason why this wasn't published on rust-analyzer.github.io as well?
