### ISSUE TITLE
rust-analyzer: Start Server not working in VSCode.

### ISSUE THREAD

**Issue by Nucl3arSn3k** [rust-analyzer/rust-analyzer.github.io#209]
When I attempt to start the rust analyzer server in VSCode through the command palette, I get a command not found error. I've tried reinstalling the extension and I run into the same issue.

**Comment by lnicola** [comment]
Which version do you have, and did you change any settings like `rust-analyzer.server.path?`

**Comment by Nucl3arSn3k** [comment]
I fixed this issue with a clean re-install of vscode.
