### ISSUE TITLE
gifs

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer.github.io#22]

**Comment by matklad** [comment]
![search-curly](https://user-images.githubusercontent.com/1711539/72264442-10acd300-361b-11ea-8d2d-0d48eff2f1c1.gif)

**Comment by matklad** [comment]
![extend-selection](https://user-images.githubusercontent.com/1711539/72265573-025fb680-361d-11ea-82d1-ccf5fe524767.gif)

**Comment by matklad** [comment]
![auto-import](https://user-images.githubusercontent.com/1711539/73185119-cf89e800-411d-11ea-9213-d6eac89256c4.gif)

**Comment by matklad** [comment]
![semantic-highlighting](https://user-images.githubusercontent.com/1711539/73185287-137ced00-411e-11ea-93ed-e415daa9c5dd.gif)

**Comment by matklad** [comment]
![assoc-completion](https://user-images.githubusercontent.com/1711539/74660243-0d66b300-5196-11ea-8327-205b1262e7a2.gif)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/75685194-77a14c80-5c9a-11ea-86b0-5ac223451b10.png)

**Comment by matklad** [comment]
![change-vis](https://user-images.githubusercontent.com/1711539/75685982-c56a8480-5c9b-11ea-84ca-a9cf07bfe0ce.gif)

**Comment by matklad** [comment]
![run-tests](https://user-images.githubusercontent.com/1711539/75686456-93a5ed80-5c9c-11ea-83b3-05adecfd07c2.gif)

**Comment by matklad** [comment]
![nav](https://user-images.githubusercontent.com/1711539/75799314-3d0de180-5d78-11ea-9531-94a38b604782.gif)

**Comment by matklad** [comment]
![arg-snippets](https://user-images.githubusercontent.com/1711539/76219227-cd837080-6215-11ea-8d0d-a9447b1d26b1.gif)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/76219505-39fe6f80-6216-11ea-9bc2-f2591388c5e6.png)

**Comment by matklad** [comment]
![assoc-completion](https://user-images.githubusercontent.com/1711539/76758522-1ee9ad80-678a-11ea-84cd-111739ecd379.gif)

**Comment by matklad** [comment]
![rename](https://user-images.githubusercontent.com/1711539/76759028-28bfe080-678b-11ea-9fb5-5ab6e6476814.gif)

**Comment by matklad** [comment]
![debug](https://user-images.githubusercontent.com/1711539/76760335-bf8d9c80-678d-11ea-80c3-8e8b12a36690.gif)

**Comment by matklad** [comment]
![merge-imports](https://user-images.githubusercontent.com/1711539/77323042-ea8b6980-6d14-11ea-8cb6-23dccafaa024.gif)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/77911990-0ef5c180-7292-11ea-9779-7ce60d8e7b2e.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/77926574-8c2b3180-72a6-11ea-90a0-e5b5b95a1f81.png)

**Comment by matklad** [comment]
![add-from](https://user-images.githubusercontent.com/1711539/78559964-8f2da100-7815-11ea-99a4-00b431df7022.gif)

**Comment by matklad** [comment]
![add-funciton](https://user-images.githubusercontent.com/1711539/78560241-111dca00-7816-11ea-89a4-5489ddf6d9dc.gif)

**Comment by matklad** [comment]
![variant-parens](https://user-images.githubusercontent.com/1711539/78560584-9a350100-7816-11ea-93ad-66bf625fcb93.gif)

**Comment by matklad** [comment]
![reorder-fields](https://user-images.githubusercontent.com/1711539/79140307-10f27100-7db8-11ea-9f3b-b246a7283bdf.gif)

**Comment by matklad** [comment]
![red](https://user-images.githubusercontent.com/1711539/79669127-af684300-81b9-11ea-9831-8bbe7993e19c.gif)

**Comment by matklad** [comment]
![old](https://user-images.githubusercontent.com/1711539/79728444-3a4a5a00-82ee-11ea-83ab-1f3e539dde69.png)
![recursive](https://user-images.githubusercontent.com/1711539/79728643-8ac1b780-82ee-11ea-867a-b231d46b89a0.png)

**Comment by matklad** [comment]
![PROOOOOOOC-MACROOOOOOOOS](https://user-images.githubusercontent.com/1711539/79734928-c57c1d80-82f7-11ea-93a5-9081087402e0.gif)

**Comment by matklad** [comment]
![run-hello-world](https://user-images.githubusercontent.com/1711539/80039323-da270400-84f7-11ea-9c16-eb9ef0a97c4c.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/80088383-b9dd6080-855c-11ea-9eb8-b527ddf97aa8.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/80091371-4be76800-8561-11ea-9975-a484c275e2db.png)

**Comment by flodiebold** [comment]
You know, whenever you post a png here I stare at it for a while waiting for it to move :wink:

**Comment by matklad** [comment]
![enums](https://user-images.githubusercontent.com/1711539/80367186-ecec6080-888a-11ea-8968-37f93424106a.gif)

**Comment by matklad** [comment]
Sadly, the animal was consumed in the process of feeding, as we don't handle references yet.

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/80368064-6e90be00-888c-11ea-9395-85d6c3371000.png)

**Comment by matklad** [comment]
![unwrap-block](https://user-images.githubusercontent.com/1711539/80965443-cf7f3f80-8e12-11ea-89e3-972503f30ca7.gif)

**Comment by matklad** [comment]
![ord](https://user-images.githubusercontent.com/1711539/80965699-4caab480-8e13-11ea-98db-6e12ffba8325.gif)

**Comment by matklad** [comment]
![change-vis](https://user-images.githubusercontent.com/1711539/81536517-fcc87200-936b-11ea-9c2b-2f561f83a4ab.gif)

**Comment by matklad** [comment]
![doctest](https://user-images.githubusercontent.com/1711539/81537179-18804800-936d-11ea-9e86-c7e6feaf38fd.gif)

**Comment by matklad** [comment]
![result](https://user-images.githubusercontent.com/1711539/81538190-b1fc2980-936e-11ea-8240-54bbd7d0dea9.gif)

**Comment by matklad** [comment]
![unwrap-block](https://user-images.githubusercontent.com/1711539/81539698-ea046c00-9370-11ea-899f-9e38238ee25b.gif)

**Comment by matklad** [comment]
![change-vis](https://user-images.githubusercontent.com/1711539/82217439-b39f9180-991a-11ea-92e9-f162c41debc6.gif)
![launch](https://user-images.githubusercontent.com/1711539/82217442-b601eb80-991a-11ea-99dd-b0c2bba786c8.gif)
![postfix](https://user-images.githubusercontent.com/1711539/82217445-b7331880-991a-11ea-8e9a-698e3dc07106.gif)
![tmod](https://user-images.githubusercontent.com/1711539/82217447-b8644580-991a-11ea-87e1-a8c61d21583f.gif)

**Comment by matklad** [comment]
![turbo](https://user-images.githubusercontent.com/1711539/82789805-3cfb1a80-9e6b-11ea-9100-a14d722d2620.gif)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/84034187-48d1fb00-a99a-11ea-960b-e6b3f73e7db1.png)

**Comment by matklad** [comment]
![named-lifetime](https://user-images.githubusercontent.com/1711539/84036167-22fa2580-a99d-11ea-8fec-493520297c3d.gif)

**Comment by matklad** [comment]
![hover](https://user-images.githubusercontent.com/1711539/84036613-b6cbf180-a99d-11ea-81e3-f3ecd9142937.gif)

**Comment by matklad** [comment]
![extract-enum](https://user-images.githubusercontent.com/1711539/84659254-6f9ead00-af17-11ea-84ab-bea16f160ecf.gif)

**Comment by matklad** [comment]
![add-field](https://user-images.githubusercontent.com/1711539/85289481-d253f380-b497-11ea-8089-2f21e3fdb75e.gif)

**Comment by matklad** [comment]
![matchig-brace](https://user-images.githubusercontent.com/1711539/86006971-122a5600-ba17-11ea-8be7-f60b0a97eead.gif)

**Comment by matklad** [comment]
![extract-field](https://user-images.githubusercontent.com/1711539/86007529-d2b03980-ba17-11ea-998f-0e44f659041f.gif)

**Comment by matklad** [comment]
![reload](https://user-images.githubusercontent.com/1711539/86605844-8335b480-bfa7-11ea-964f-72e06f535607.gif)

**Comment by matklad** [comment]
![combined](https://user-images.githubusercontent.com/1711539/87071611-bdf35300-c21a-11ea-93d6-c04f1b1a8ac1.gif)

**Comment by matklad** [comment]
![completions](https://user-images.githubusercontent.com/1711539/87296648-60efe980-c507-11ea-95d5-9b66623e2636.gif)

**Comment by matklad** [comment]
![auto-relaod](https://user-images.githubusercontent.com/1711539/87297466-c4c6e200-c508-11ea-9fb0-519757220b5d.gif)

**Comment by matklad** [comment]
![turbo-fish](https://user-images.githubusercontent.com/1711539/87852942-8f563600-c906-11ea-808b-63e8bf3fc228.gif)

**Comment by matklad** [comment]
![onenter](https://user-images.githubusercontent.com/1711539/87931694-7d050500-ca8a-11ea-8b3f-c958663795e6.gif)

**Comment by matklad** [comment]
![merge-imports](https://user-images.githubusercontent.com/1711539/90399497-5216cc80-e09b-11ea-8fea-e03ebc2f250e.gif)

**Comment by matklad** [comment]
![features](https://user-images.githubusercontent.com/1711539/91040123-feadfc80-e60d-11ea-8f7c-3d0e76e59f5b.gif)

**Comment by matklad** [comment]
![rename](https://user-images.githubusercontent.com/1711539/91040131-040b4700-e60e-11ea-97ae-7d1819466cb1.gif)

**Comment by matklad** [comment]
![remove-unused-param](https://user-images.githubusercontent.com/1711539/91040554-bfcc7680-e60e-11ea-905f-548c4308246a.gif)

**Comment by matklad** [comment]
![links](https://user-images.githubusercontent.com/1711539/91714233-91f5ad80-eb8b-11ea-8149-d9eeaf8150f9.gif)

**Comment by matklad** [comment]
![inline](https://user-images.githubusercontent.com/1711539/91714758-aa19fc80-eb8c-11ea-82af-8b86941ca23c.gif)

**Comment by jonas-schievink** [comment]
![async-blocks](https://user-images.githubusercontent.com/1786438/93090569-3b18c980-f69d-11ea-872c-c3bbf99b2438.gif)

![box-pat](https://user-images.githubusercontent.com/1786438/93090576-3fdd7d80-f69d-11ea-95e9-8e1866f23c23.gif)

![complete-mod](https://user-images.githubusercontent.com/1786438/93090591-466bf500-f69d-11ea-9a8c-f054a693287f.gif)

**Comment by matklad** [comment]
![comp-ref](https://user-images.githubusercontent.com/1711539/94450567-b7d39980-01ad-11eb-9a81-08717c9f76f6.gif)

**Comment by matklad** [comment]
![dbgr](https://user-images.githubusercontent.com/1711539/94450989-33cde180-01ae-11eb-877a-6651124a707c.gif)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/95746625-63ddb000-0c97-11eb-83d1-5f3e2fb997f6.png)

**Comment by matklad** [comment]
![vis](https://user-images.githubusercontent.com/1711539/96458761-9a7c7300-1221-11eb-8243-1c722cc8b614.gif)

**Comment by matklad** [comment]
![qual-path](https://user-images.githubusercontent.com/1711539/97172657-9c998100-178f-11eb-89de-172af96d0301.gif)

**Comment by matklad** [comment]
![replace-with-char](https://user-images.githubusercontent.com/1711539/97172891-fe59eb00-178f-11eb-80ce-57502898920b.gif)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/97173004-29dcd580-1790-11eb-8bbc-932dd27a1e05.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/97173470-eafb4f80-1790-11eb-87a4-cb3f2407a2d8.png)

**Comment by matklad** [comment]
continuing the party at #77
