### ISSUE TITLE
Binary name confusion in the docs?

### ISSUE THREAD

**Issue by filmil** [rust-analyzer/rust-analyzer.github.io#36]
Compiling `rust-analyzer` from source gives me a binary called `rust-analyzer`.

And yet, the instructions here: https://rust-analyzer.github.io/manual.html#vim talk about a binary `ra_lsp_server`.  Are these one and the same binary? 

If so, shouldn't there be just one binary name?

**Comment by flodiebold** [comment]
The binary name has been changed recently; the docs need to be updated to also say `rust-analyzer`.
