### ISSUE TITLE
Markup broken on Installation page

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer.github.io#38]
In the **VS Code** and **Updates** sections of the [User Manual](https://rust-analyzer.github.io/manual.html) are sections with a left column saying `:INFORMATION _SOURCE:`. This is rendered as a bold lowercase `i` on GitHub, but not on the website.

Screenshot in Firefox:

![Screenshot_20200414_213932](https://user-images.githubusercontent.com/15658558/79266943-a5340500-7e98-11ea-98e0-ea2fea28a2e9.png)

**Comment by Aloso** [comment]
It's better now:

![fa](https://user-images.githubusercontent.com/15658558/79689803-65ce3580-8257-11ea-8b16-ae5d0d7056ff.png)

But the icon is still not displayed properly. I suspect this is because the [fontawesome](https://fontawesome.com/) library is not included in the website:

```html
<td class="icon">
<i class="fa icon-note" title="Note"></i>
</td>
```

**Comment by matklad** [comment]
fixed this some time ago. We still need make overlofing code boxes prettier thoguh...
