### ISSUE TITLE
Supported vscode versions in readme

### ISSUE THREAD

**Issue by HKalbasi** [rust-analyzer/rust-analyzer.github.io#88]
Seems the vscode extension have problem with vscode version 1.50.1. Please write this and supported versions in readme (or a better place which I don't know) so people can upgrade/downgrade they vscode.

**Comment by flodiebold** [comment]
This is the repository for the website; this should be reported at https://github.com/rust-analyzer/rust-analyzer.

That said, the manual [mentions](https://rust-analyzer.github.io/manual.html#installation) our supported versions:
> Note that we only support two most recent versions of VS Code.
